name: .NET

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04,windows-2019,macos-10.15]
        # os: [ubuntu-18.04,windows-2019,macos-10.15]
    steps:
      - name: 'mk text'
        run: |
          touch test.txt
          echo "mol" > test.txt

      - name: 'win'
        if: runner.os == 'Windows'
        run: |
          touch test_win.txt
          echo "mol win" > test.txt
          echo "mol win" > test_win.txt

      - name: 'linux'
        if: runner.os == 'Linux'
        run: |
          touch test_linux.txt
          echo "mol linux" > test.txt
          echo "mol linux" > test_linux.txt

      - name: 'mac'
        if: runner.os == 'Macos'
        run: |
          touch test_mac.txt
          echo "mol mac" > test.txt
          echo "mol mac" > test_mac.txt

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            *.txt
            *.jar

#    steps:
#      - uses: actions/checkout@v2
#      - name: Setup .NET
#        uses: actions/setup-dotnet@v1
#        with:
#          dotnet-version: 5.0.x
#      - name: Restore dependencies
#        run: dotnet restore
#      - name: Pack
#        run: dotnet pack